### ISSUE TITLE
Issue sending Email using Kubernetes Service

### ISSUE THREAD

**Issue by chrisblatt** [bokysan/docker-postfix#108]
I have setup a pod which runs a custom app and it has postfix installed, I have set it up as a Satellite System to use this helm chart's postfix server to send emails about app performance
My config:
- raspberry pi cluster running k3s
- using Gmail smtp
- a personal gmail email address
- app token for password

My issue:
If I setup my app to send emails through the kubernetes service via DNS I get a connection timed-out error, but if I setup it to send emails through the postfix pod IP address it sends successfully. Is there something I need to configure to allow the service to work?

**Comment by bokysan** [comment]
Not quite sure if this can be helped in the scope of this project, this sounds more like an issue with your kubernetes setup.

The Helm chart [deploys a service](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/templates/service.yaml) and your postfix should be accessible on this address.

E.g. if your namespace is `mail` and your deployment name is `postfix`, you should be able to send mail by connecting to `postfix.mail.svc.cluster.local:587`. And I know this for a fact as I'm using the same chart in several environments, and they work.

I'm sorry but given existing data I cannot help you further other than to suggest going through Kubernetes documentation. :-(
