### ISSUE TITLE
DKIM not working

### ISSUE THREAD

**Issue by dshepherd2** [bokysan/docker-postfix#109]
What is the best way to log dkim in this image. Judging by email headers at the desitination dkim is not functioning. I am very much an email newbie at this level so any clues to see any log messages on dkim would be appreciated.

Many thanks

David

**Comment by bokysan** [comment]
Dear David,

DKIM is a bit complex beast. You need to set up your DNS records as well.

This image tries to automate the process as much as possible. If you haven't done so, I do suggest looking at [README.md](https://github.com/bokysan/docker-postfix#dkim--domainkeys) how to setup DKIM with this image. You can also enable additional play with [opendkim.conf](https://wiki.debian.org/opendkim) settings by setting variables `OPENDKIM_*`, e.g. `OPENDKIM_LogWhy=true`, `OPENDKIM_SysLog=true` and similar.

However much I would like to help you set up your DKIM I am but one guy and don't have enough resources to do that (and you haven't provided enough information). I suggest you look at some [general tutorials](https://www.google.com/search?q=postfix+dkim+setup) on how to set up DKIM with Postfix and start of there.
