### ISSUE TITLE
DKIM do not work. The rights of opendkim folder are wrong

### ISSUE THREAD

**Issue by zdreicom** [bokysan/docker-postfix#11]
going into the docker container and execute

* chown -R opendkim. /etc/opendkim
* chmod go-rw /etc/opendkim/keys

helps. The problem is it is not persistent.

Sugesstion: Using a different folder to link the keys in the container. Doing the start the keys can be copied and processed. After this the rights can be changed without changing the rights in the host system

**Comment by bokysan** [comment]
I've though about this long and hard and I'm leaning towards not doing it.

E.g. with Kubernetes you can bind a `ConfigMap` folder and copying on the start won't reflect the changes and can lead to hard-to-spot issues.

Maybe a better solution would be to add support for custom init scripts where you could do this yourself, it needed.

**Comment by vicmosin** [comment]
@bokysan Any update regarding the issue? Custom scripts sounds more generic solution

**Comment by dacrhu** [comment]
smtp   | ‣ NOTE: Configuring OpenDKIM.
smtp   |         ...using socket inet:localhost:8891
smtp   |   ...WARN: skipping for domain "mydomain.com". File /etc/opendkim/keys/"mydomain.com".private not found!

If I rename my private key to "mydomain.com".private then working fine.
So in the container the script find wrong filename.

**Comment by bokysan** [comment]
I will most likely fix this in the next update.

**Comment by vicmosin** [comment]
@bokysan any updates? Current docker image still has an issue

**Comment by bokysan** [comment]
Can you please try with the latest image from master, as `opendkim.conf` settings now include `RequireSafeKeys=no`, which shouldn produce this error anymore?

**Comment by bokysan** [comment]
Closing as this shouldn't be an issue anymore.
