### ISSUE TITLE
Example on how to provide existing DKIM signature via Helm

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [bokysan/docker-postfix#113]
Hi,

I'm trying to make it work that I can provide existing DKIM signatures for docker-postfix via the Helm Chart, but can't get it running.

Could you provide an example?
Do I have to specify the mountSecret?

**Comment by bokysan** [comment]
You can use [extraVolumeMounts](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/values.yaml#L59) to mount `/etc/opendkim/keys`.

See [test_04_common_config.yml](https://github.com/bokysan/docker-postfix/blob/master/helm/test_04_common_config.yml#L26).
