### ISSUE TITLE
Unit tests: can't build due to invalid referenced package cyrus-sasl-static (Alpine latest)

### ISSUE THREAD

**Issue by fizzyduck** [bokysan/docker-postfix#114]
Hi,

Thanks for creating this project.

I can't run the unit tests on a fresh checkout due to the package cyrus-sasl-static which appears to be missing in Alpine latest.

If I remove this package I can get the unit tests to start.

Is this expected behaviour or has this packaged been removed from later Alpine versions?

**Comment by fizzyduck** [comment]
This doesn't match with the actual build `build-scripts/postfix-install.sh` which doesn't appear to need these changes.

Could these be pulling different alpine images? Should the unit tests use the same build process as the main build to keep things consistent?

**Comment by bokysan** [comment]
How exactly are you running these tests?

I simply do not have enough information on this issue to answer properly.

**Comment by bokysan** [comment]
I'm closing this issue as I did not receive futher information.
