### ISSUE TITLE
CVEs related to Alpine version 3.16.0

### ISSUE THREAD

**Issue by noahlz** [bokysan/docker-postfix#123]
Artifact Hub is helpfully reporting a number of CVEs in the current release (3.5.1). It seems like this might be simply a matter of bumping the Alpine Linux version? 3.17.0

https://artifacthub.io/packages/helm/docker-postfix/mail?modal=security-report

**Comment by bokysan** [comment]
Yes, I will publish a newver version of the image soon.

**Comment by bokysan** [comment]
Ne version published, based on `alpine:latest`, which at this time is `3.17.2`.
