### ISSUE TITLE
Ability to not set timezone on container bootup

### ISSUE THREAD

**Issue by samip5** [bokysan/docker-postfix#125]
Currently the container will fail to boot if the localtime has already been set before it's ran.
Please add an ability to the setup_timezone function to just skip it all together with a env variable on container start.

For reference:
```
★★★★★ POSTFIX STARTING UP ★★★★★
‣ NOTE  Setting container timezone to: Europe/Helsinki
ln: /etc/localtime: File exists
```

It doesn't get past that.

**Comment by bokysan** [comment]
Of couse -- sounds easy enough. Pull requests are welcome.

**Comment by bokysan** [comment]
So, if you [look at the code](https://github.com/bokysan/docker-postfix/blob/master/scripts/common-run.sh#L8), timezone is set only if you set the `TZ` variable.

If that doesn't exist, it's not set. So just remove the variable from your boot and you should be good.
