### ISSUE TITLE
Not able to send email. 

### ISSUE THREAD

**Issue by kiranpatilwk** [bokysan/docker-postfix#128]
I am using helm chart using ses credentials and mails are getting stuck at queue.
**Queued mail for delivery**

**Comment by bokysan** [comment]
Hi,

sorry I have missed this issue. I am closing it, though, as:
- I have simply not enough to go on to even try to help you
- This sounds like a postfix issue, not a packaging thing

I can only suggest that you check out your log files, check Amazon logs (SES can be configured to deliver logs to CloudWatch) and if you're still facing an issue, get help from a local postfix expert.

Good luck!
