### ISSUE TITLE
Examples or reference to use postfix

### ISSUE THREAD

**Issue by anthony-halim** [bokysan/docker-postfix#13]
Hi,

First of all, thank you so much for the image! I have spent days looking for a simple, usable postfix in my project and yours works wonderfully. 

As the title says, will it be possible to include examples on how to use postfix inside the README file just to check that postfix is in order? Thank you very much!

**Comment by bokysan** [comment]
You are welcome. 😊

What kind of examples are you looking for, specifically? As must things are already in the README and configured using environment variables.

**Comment by anthony-halim** [comment]
Perhaps, a way to confirm that networks in `mynetworks` are able to relay emails through the `relayhost`? That will be great!

P.S I am sorry if the question does not make sense, I am still learning the mailing system in general.

**Comment by bokysan** [comment]
1. Go to the server which is in `mynetworks`
2. Use any SMTP-capable client and try to send email (e.g. `sendmail`) or just use `telnet`:
```
telnet smtp-server 25
HELO dolly
MAIL FROM:anthony@domain.com
RCPT TO:anthony@gmail.COM
DATA
Subject: Test
Content-Type: text/plain

Hello from telnet
.
QUIT
```

If your SMTP server is not configured successfully, you won't be able to do this. If you DNS / SPF is not configured properly, mail will be accepted, but will not be forwarded to Gmail.

**Comment by anthony-halim** [comment]
> 1. Go to the server which is in `mynetworks`
> 2. Use any SMTP-capable client and try to send email (e.g. `sendmail`) or just use `telnet`:
> 
> ```
> telnet smtp-server 25
> HELO dolly
> MAIL FROM:anthony@domain.com
> RCPT TO:anthony@gmail.COM
> DATA
> Subject: Test
> Content-Type: text/plain
> 
> Hello from telnet
> .
> QUIT
> ```
> 
> If your SMTP server is not configured successfully, you won't be able to do this. If you DNS / SPF is not configured properly, mail will be accepted, but will not be forwarded to Gmail.

After DATA,
I need to write
```
from: anthony@domain.com
to: anthony@gmail.com
subject: Test

content
.
QUIT
```
This is because the email sent by some SMTP(e.g gmail) need to RFC 5322 compliant and require the ```From``` header. Else, it will be marked as a spam and will be not received.

Just helping those who need! Did not test whether ```to``` and ```subject``` are mandatory though.
