### ISSUE TITLE
587 does not use TLS

### ISSUE THREAD

**Issue by Tipsmark** [bokysan/docker-postfix#130]
hi there, 587 seems to be plain text, no enryption - how do I enable encryption so clients must use startls or TLS? I'd also like to open port 25 for unenrypted legacy clients

**Comment by bokysan** [comment]
Hi,

you need to read [Postfix documentation](https://www.postfix.org/TLS_README.html), which is outside my help.

You can check out the [examples](https://github.com/bokysan/docker-postfix/blob/master/examples/docker/mail-station/docker-compose.yml#L94) folder, though, to get you started. You basically need to provide a certificate if you want encrypted connections. That cannot be configured automagically.

If you need Postfix to listen on port 25, you need to change `master.cf`. [Google is your friend](https://www.google.com/search?q=postfix+listening+port).
