### ISSUE TITLE
Build failed in mount stage

### ISSUE THREAD

**Issue by SerheoReutty** [bokysan/docker-postfix#133]
Hello! Please, help me. i am use our project long time, since 2021 years. I'm trying update my instance. Clone last release version and trying build, but i have this error.
What is it, how i can fixed this error?
``` => ERROR [base 2/2] RUN        --mount=type=cache,target=/var/cache/apt,sharing=locked,id=var-cache-apt-linux/am  0.3s
------
 > [base 2/2] RUN        --mount=type=cache,target=/var/cache/apt,sharing=locked,id=var-cache-apt-linux/amd64
 --mount=type=cache,target=/var/lib/apt,sharing=locked,id=var-lib-apt-linux/amd64            --mount=type=tmpfs,target=/var/cache/apk            --mount=type=tmpfs,target=/tmp            --mount=type=bind,from=build-scripts,source=/build-scripts,target=/build-scripts            sh /build-scripts/postfix-install.sh:
#9 0.291 /build-scripts/postfix-install.sh: set: line 2: illegal option -
------
executor failed running [/bin/sh -c sh /build-scripts/postfix-install.sh]: exit code: 2```

**Comment by bokysan** [comment]
Ok,

you have given me too little information to actually go on anything. I have no idea how you're building this, on which environment and why you are even trying to build it as you could be using the [prebuilt image](https://hub.docker.com/r/boky/postfix/) instead.

Either way, second line of `/build-scripts/postfix-install.sh` is [`set -e`](https://github.com/bokysan/docker-postfix/blob/master/build-scripts/postfix-install.sh#L2), so my best guess is that you are running a build on shell that does not support `set -e`. See [`man set`](https://man7.org/linux/man-pages/man1/set.1p.html).
