### ISSUE TITLE
Helm chart update for headless service

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [bokysan/docker-postfix#140]
Hello Bokysan, 

First thanks you for the awsome work on this project.

issue is regarding deployment on kubernetes, and compliance with the kubernetes documentation regarding statefulset.

seems a headless service is required now [Documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)

Manage to deploy by adding a new service-headless.yaml file : 

`{{- $chart := "mail" -}}
{{- $fullName := include (print $chart ".fullname") . -}}
{{- $labels := include (print $chart ".labels") . -}}
{{- $selectorLabels := include (print $chart ".selectorLabels") . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ print $fullName "-headless" | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $labels | nindent 4 }}
    {{- with .Values.service.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  annotations:
    {{- with .Values.service.annotations }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
      {{ if eq .Values.service.type "NodePort" }}nodePort: {{ .Values.service.nodePort }}{{ end }}
  selector: 
    {{- $selectorLabels | nindent 4 }}
`

Best regards,

**Comment by bokysan** [comment]
I'm preparing to release a new version soon, I will add this to the list. Thank you.
