### ISSUE TITLE
Out of spec line length causes postfix to break DKIM signature

### ISSUE THREAD

**Issue by BFriedrichs** [bokysan/docker-postfix#142]
I had an issue with my DKIM breaking seemingly randomly, and it took me a while to debug this.

It seems that to adhere to the email specification postfix automatically adjusts an emails body if one line exceeds 998 bytes.
You can see this in the logs:
```
opendkim: DKIM-Signature field added (s=email, d=mail.domain.com)
[...]
postfix/smtp: breaking line > 998 bytes with <CR><LF>SPACE
```
Since the DKIM signature has been already computed this of course then breaks once it gets checked.

Naturally the immediate fix is to change the original emails instead of relying on postfix here, but also I think it would be nice to  adjust the order of this within the container? I haven't really dug into your source and I'll see if I can craft a PR, but I could see how this might be just an issue with postfix itself.

--

Completely unrelated but maybe just to let you know - this is running on `mail.domain.com` unlike stated as an issue here https://github.com/bokysan/docker-postfix/issues/111.

**Comment by bokysan** [comment]
Thanks for reporting here issue.

I believe I understand the problem - if I follow, this happens if you use this image as a forwarder (so DKIM headers are already in the email once received by postfix)?

Not quite sure if I understand the solution:

> I think it would be nice to adjust the order of this within the container

What exactly did you mean by this?

Thanks,
B

**Comment by BFriedrichs** [comment]
Hey, first of all thank you for the fast response. I must admit I am not really knowledgeable with any of this, but I did some digging and I think you are correct. Opendkim is added as a milter to the postfix smtp-only "before-queue", so the headers are written already.

As far as I understand there is actually no way to change this behaviour either (or at least not easily at all) and I don't think it would be really within the scope of what you are achieving here. Instead I'll just adjust my line lengths before sending.

Let me know if I'm off the mark with this though, you will certainly have a much better idea of what is going on.

**Comment by bokysan** [comment]
> I don't think it would be really within the scope of what you are achieving here.

That's exactly the case. I'm just a maintainer of the packaging system, postfix itself is another story.

If there's a quick and dirty way to fix this with defaults of the image (while not breaking anything) I'm all for it. But frankly, I don't know ATM.

**Comment by bokysan** [comment]
I'm closing this issue for the time being -- if you find anything that could actually be change in the image, please let me know and we can reopen.
