### ISSUE TITLE
Possibility to use transport maps

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#143]
We´re currently trying deploy Postfix to K8s with your Helm Chart. We have the requirement to route the emails to different relay hosts and therefore we need to use transport maps. 
So we need a custom transport file in /etc/postfix and transport_map entry in the main.cf. 

Is this possible with the actual Helm chart?

**Comment by bokysan** [comment]
Yes.

See example [here](https://github.com/bokysan/docker-postfix/blob/master/examples/docker/mail-station/docker-compose.yml#L126C4-L126C4).

**Comment by frankhetterich** [comment]
Hi,
 your example is pointing to the "sender_dependent_relayhost" but we need a "recipient_dependent_relayhost" mapping. 

Your example is Docker based and is using a file mapping from the Docker Host into the container. But this is not possible in Kubernetes.

**Comment by bokysan** [comment]
Kubernetes example is available [as well](https://github.com/bokysan/docker-postfix/blob/master/examples/kubernetes/aws-ses-with-google-values.yml#L63).


Specifically:
- set `config.posrfix.recipient_dependent_relayhost=lmdb:/etc/postfix/...`
- bind a file into pod via `ConfigMap`
- `postmap` will be automatically called on these files. 


If you need to fidlle with anything some more, you can create a startup file as seen in the example above.
