### ISSUE TITLE
Default database type in V4.0.1 changed from lmdb to hash?

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#151]
It looks like the Postfix default database type changed from lmdb to hash in the new V4.0.1 release. Whe´re using the HELM chart to deploy to K8s. 

Whe´re using a transport_maps entry `transport_maps: "lmdb:/etc/postfix/recipient_dependent_relayhost"` which is not working any more in the new release. 
When i add `postfix.default_database_type: "lmdb"` to the values.yaml  it works as before. 

There is also a Warning in the logs which i did not spot in older releases: 
`warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol`

**Comment by bokysan** [comment]
Can you please open a separate ticket for `inet_protocols: disabling IPv6 name/address support` and add your exact configuration so I can replace this, as I have not encountered this in my testing.
