### ISSUE TITLE
helm chart startup probe fails due to `exec` in opendkim.sh

### ISSUE THREAD

**Issue by lwj5** [bokysan/docker-postfix#152]
The startup probe `ps axf | fgrep -v grep | fgrep -q 'opendkim.sh'` should be replaced with `ps axf | fgrep -v grep | fgrep -q 'opendkim'`

as `exec` is used in opendkim.sh

**Comment by bokysan** [comment]
Thanks, fixed in the latest master, will make it to `v4.0.2`.
