### ISSUE TITLE
Service and Headless Service are using the same values in Helm Chart

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#154]
Since Version 4.0.1 there is an additional headless service deployed. The headless service is using the same values as the "normal" service. 

Background: We exposing postfix via service type "LoadBalancer" and setting a fixed IP with an annotation.  
But the Value `service.annotations` is used for both services and this leads to problems, because both services are trying to use the same external IP address.

**Comment by bokysan** [comment]
Fixed in `master`.
