### ISSUE TITLE
Suggestion: Add "copytruncate" parameter to logrotate configuration

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#158]
We are running docker-postfix in K8s using the provided HelmChart.  

Since we have activated the prometheus metrics, an additional postfix log file is generated for the prometheus exporter. 
In our productive environment we had the problem that Postfix did not write anything to the new log after the log update and therefore not all metrics were available anymore. 
We have now added the "copytruncate" parameter to the logrotate configuration in values.yaml. 
Since then there have been no more problems. 

IMHO it makes sense to add this parameter to the values.yaml.

**Comment by bokysan** [comment]
I agree. Will be fixed in the next release.
