### ISSUE TITLE
Startup error: "fatal: /usr/lib/postfix/postfix-script: No such file or directory"

### ISSUE THREAD

**Issue by mhavelant** [bokysan/docker-postfix#16]
Hi!

When starting the docker image `boky/postfix:v1.1.3`, I get the above error.
`postfix[41]: fatal: /usr/lib/postfix/postfix-script: No such file or directory`

I looked for it and there is one located at `/usr/libexec/postfix/postfix-script`, but that doesn't seem to work when copied over.

**Comment by bokysan** [comment]
That's funny -- I can confirm it works on my machine.

Can you share how exactly you're starting it on your end?

**Comment by mhavelant** [comment]
I have it set up in docker-compose:
`  
mail_server:
    image: boky/postfix:v1.1.3
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_mail_server"
    environment:
    - "HOSTNAME=${MAIL_SERVER_HOSTNAME}"
    - "ALLOWED_SENDER_DOMAINS=${MAIL_SERVER_ALLOWED_SENDER_DOMAINS}"
    networks:
    - mail_server
`

However, I just did the old "remove it completely and restart it" trick, and it works now.
For future reference, this issue came after I upgraded from a very old (pre 1.0) version to this. Apparently, docker-compose stating that it's recreating things doesn't seem to work properly.
