### ISSUE TITLE
With v4.0.2 the default for smtpd_tls_security_level has changed it seems

### ISSUE THREAD

**Issue by EraYaN** [bokysan/docker-postfix#160]
So with v4.0.2 the `smtpd_tls_security_level` default has changed (on the client side). So it might be worth adding some of these changes (potential debian vs alpine differences?) to the change log entry for v4 in the readme. It took a while before we knew what the problem was.

Setting it to `none` fixed our no-TLS configuration within our application cluster. (Application services communicate without using TLS with the SMTP container)

**Comment by bokysan** [comment]
You are correct. Added to changeset for v4.0.0.
