### ISSUE TITLE
Authenticate Relay on "LAN" side

### ISSUE THREAD

**Issue by LewisSpring** [bokysan/docker-postfix#161]
Hey there!

Just finished setting up the container, well done, it's really good!

I might just be missing something, but is it possible to configure a username and password on the LAN side of the relay?

I am using the Gmail relay and the latest version of the container.

Cheers

**Comment by bokysan** [comment]
If your question is: "Hi, I would like my client accessing this Postfix service to authenticate using username/password to send email" then yes, this is certainly doable.

This is out of scope of this image, as this is specific configuration of Postfix: [Google is your friend](https://www.google.com/search?q=postfix+configure+authentication).

In short:
- you need to decide what kind of authentication backend you will have (Postfix supports many)
- you need to store credentials in that backend
- you need to configure postfix (through `main.cf` + potentially additional files) to use that backend

Most likely, a simple file-based backend with "hardcoded" usernames and passwords will cover your use case.

**Comment by bokysan** [comment]
There's the (unsafe) `SMTPD_SASL_USERS` which could probably fit your bill.
