### ISSUE TITLE
Enabling nodeport breaks the headless service

### ISSUE THREAD

**Issue by jonathon2nd** [bokysan/docker-postfix#163]
Hello! I'm back :D

Enabling nodeport causes the deployment to fail, as the [headless service](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/templates/service.yaml#L49) has the nodeport if enabled. Which does not work IIRC.

values
```
...
service:
  type: NodePort
  nodePort: 30027
...
```

![image](https://github.com/bokysan/docker-postfix/assets/52681917/a9056861-0c7c-404e-a104-39ac3cdcb6fc)

![image](https://github.com/bokysan/docker-postfix/assets/52681917/e10f1076-529e-4c98-bb28-eeec8097c5fd)

**Comment by jonathon2nd** [comment]
What I have done for now is remove the nodeport from values, and manually set it up. That way I can go ahead and switch over to upstream helm and get everything tested.

**Comment by bokysan** [comment]
You are correct -- Fixed in commit `b317e68e28d449191b3d58dfbe00c66085f1986b`.
