### ISSUE TITLE
README - Incorrect UID/GID in Security

### ISSUE THREAD

**Issue by itounch** [bokysan/docker-postfix#169]
README says : `Postfix will run the master proces as root, because that's how it's designed. Subprocesses will run under the postfix account which will use UID:GID of 100:101. opendkim will run under account 102:103.`

But in reality, opendkim run under account 103:104

I'm using the 4.0.2 release (boky/postfix:latest)

**Comment by bokysan** [comment]
Hi,

I will check it out, might have to do something with different distributions.
