### ISSUE TITLE
Docker healthcheck reports unhealthy due to syntax error

### ISSUE THREAD

**Issue by samsapti** [bokysan/docker-postfix#172]
The `nc` command in the healthcheck has a syntax error, resulting in the following error message:

```
nc: service "-w" unknown
```

The fix is to change `nc 127.0.0.1 587 -w 2` to `nc -w 2 127.0.0.1 587`.

**Comment by bokysan** [comment]
That's on me. I've merged PR #171 without proper testing. Will fix.
