### ISSUE TITLE
Not able to get the smtp-relay pod in ready state

### ISSUE THREAD

**Issue by tardich** [bokysan/docker-postfix#174]
Running the mail relay from the provided helm chart, I'm facing an issue which do not let the pod reach the ready state.

In the pod logs, everything seems normal, but describing the pod, I'm getting:

> Readiness probe failed: command "sh -c [ ! -f /tmp/container_is_terminating ] && printf \"EHLO healthcheck\\nquit\\n\" | { while read l ; do sleep 1; echo $l; done } | nc -w 2 127.0.0.1 587 | grep -qE \"^220.*ESMTP Postfix\"" timed out

Any clue on where to look at?

Nice work, by the way!

**Comment by tardich** [comment]
In case you ask, I'm using mail-4.0.4, using default image from it

**Comment by tardich** [comment]
As I can see, the error is the script itself. Running it in a shell all by itself returns:

!: line 1: [: missing `]'

I haven't found out yet the issue with it....

**Comment by bokysan** [comment]
Yeah, this is all connected to #171 -- I'll need to fix the issue and test it out thorougly.

**Comment by bokysan** [comment]
I believe issue has been fixed. Can you please try `edge` image?

You'll also need to do `helm ... --set readinessProbe.timeoutSeconds=8` to test this. This will be the default in release `v4.1.0`.

**Comment by tardich** [comment]
Yes, it now works! Great !
