### ISSUE TITLE
Would you consider supporting tags for Alpine versions?

### ISSUE THREAD

**Issue by mcritchlow** [bokysan/docker-postfix#19]
Hi there,

I'm using your image at the moment in a Kubernetes context, and working on potentially building a Helm chart around your container image so I can re-use it easily in different projects.

We try and pin our container image `FROM`'s whenever possible, and thus ideally I'd prefer not to rely on an image that uses `latest` in production.

So I was wondering if you would consider supporting tagged images that perhaps support `latest` and maybe one or two versions of Alpine such as `3.10` (latest) and `3.9` (latest - 1)?

I think this could be scripted up fairly easily with what you already have in this repo, perhaps by updating the Dockerfile to include:

```
ARG alpine_version=latest
FROM alpine:$alpine_version
.....
```

Thanks for considering!

**Comment by bokysan** [comment]
Hi,

sure, why not. If you're willing to post a pull request, I'd be happy to review and include it in the project.

I would, however, need to see what would be the best way to build and push this to Docker hub.
