### ISSUE TITLE
Using GMail as Relay: Way to generate tokens in README not working anymore

### ISSUE THREAD

**Issue by humanbeinc** [bokysan/docker-postfix#191]

**Comment by bokysan** [comment]
Hi,

I would love to help out here, but you have given me no information on which I can start the investigation.

Please kindly update this issue with the details, e.g.:
- image you're using
- what are you trying to achieve
- what are the steps to reproduce the issue
- what is the expected outcome
- what is the actual outcome

If you can also provide a solution / workaround, that would be very much appreciated as well, as it makes my end much easier!


Cheers,
B

**Comment by bokysan** [comment]
CLosing as there was no futher feedback.
