### ISSUE TITLE
SASL passwords are created with the container's hostname as domain

### ISSUE THREAD

**Issue by thielj** [bokysan/docker-postfix#192]
Current `boky/postfix:latest-alpine`, postfix v3.8.4.

I've been trying to force authentication using SMTPD_SASL_USERS="user:pass". However, it didn't work as expected. Long story short, this is what ended up in sasldb

```Shell
51686ed8d2b4:/tmp# sasldblistusers2
user@51686ed8d2b4: userPassword
```

When I use `user@<containername>` it all works as expected - except that the mail is bounced by Gmail and probably others (_'From' header has non compliant domain name_). I tracked this down to `postfix_setup_smtpd_sasl_auth()` in `common-run.sh`. It might need changing like this (see [SASL_README](https://www.postfix.org/SASL_README.html#auxprop_sasldb)):

```Shell
    echo $_pwd | saslpasswd2 -p -c -u `postconf -h mydomain` $_user
```

When used in conjunction with the below, postfix would accept both `user` and `user@example.com` as valid user names.

```
    POSTFIX_smtpd_sasl_local_domain:          "$$mydomain"
```

Another option would be to specify `SMTPD_SASL_USERS='user@example.com:password,...'`, which I've started using now. If the behaviour on other platforms is the same, it might be worth adding this to the README where it mentions SMTPD_SASL_USERS.

---

Speaking of other platforms, there's probably another issue in this function. When using the Debian based image `boky/postfix:latest` with SMTPD_SASL_USERS, the container keeps restarting:

```
--------8<-------------
‣ INFO  Enable smtpd sasl auth.
ln: failed to create symbolic link '/etc/sasl2/smtpd.conf': File exists
★★★★★ POSTFIX STARTING UP (debian) ★★★★★
‣ NOTE  Setting container timezone to: Etc/UTC
--------8<-------------
```

A simple check if this file exists or using `ln -s -f` might fix it. They both look identical, I haven't investigated any further than this.

---

Many thanks for providing this image, by the way!

**Comment by bokysan** [comment]
Hi,

thanks for this detailed report. You are, in fact, correct. The documentation was not clean enough on that part.

The [latest commit](https://github.com/bokysan/docker-postfix/commit/b358d714542af280115fa22845f505ea34a93e88) to master should have this fixed. Please do kindly test and let me know if you run into any additional issues.

**Comment by bokysan** [comment]
> I think the bad users handling is unnecessary, i.e. you can always pass a sensible domain default, and the user can override this if desired:

The problem is legacy. If users are already using it as-is they won't notice the change and will complain why authentication stopped working all of a sudden.

**Comment by bokysan** [comment]
> Also, it would be helpful to call sasldblistusers2 at the end to log the added user accounts.

Generally not the best idea to log the passwords on the console. True, they are provided as environment variables, but in Kubernetes, for example, they can read from `Secret`s so they are semi-hidden, at least.

Logging them directly into console at startup seems really bad to me.

**Comment by bokysan** [comment]
> Do you want a pull request? ;)

That would be nice, yes. Thank you. 🙂

**Comment by bokysan** [comment]
> Another thought: switching between base images and keeping the same volume for /var/spool/postfix might be a source of spurious errors. I've seen this in other issues and experienced them myself. Wouldn't it be a good idea to zap any existing etc and usr directories when setting up the chroot? Or at least putting a warning in the docs and examples?

Agreed. When I created alternate images I did not imagine that people would be switching between them back and forth. But your tool does get used in ways you've never expected. When starting you do get a warning but it would be prudent to add to docs that you should be doing this only if you *really know* what you're doing.

I'm against deleting anything, though - this is not something you'd expect an image to do and can come back and bite you in the a**. If anything I'd opt for killing the image and letting the user deal with this on his own.

I'll open another ticket on the topic if I just don't fix it in one commit.
