### ISSUE TITLE
prometheus without k8s

### ISSUE THREAD

**Issue by llaumgui** [bokysan/docker-postfix#193]
Hi,

it would be fine to can enable prometheus feature without using k8s (docker-compose).

Best regards.

**Comment by bokysan** [comment]
Hi.

Prometheus is implemented as a [sidecar container](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/templates/statefulset.yaml#L136). In other words: it runs a separate docker image which consumes the logs from Postfix itself.

This is technically not feasible to do inside a single image, without building and pulling in the whole [kumina/postfix_exporter](https://github.com/kumina/postfix_exporter) image.

You can, however, implement it yourself by running a second container inside `docker-compose.yaml`, based on the example [in the chart](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/templates/statefulset.yaml#L136). There are some tweaks as you need to:
- redirect Postfix output to a file
- ensure that that file is still reported to standard out of the Postfix image (for debugging / control)
- ensure that your `postfix_exporter` consumes the proper output file

With all of that, there's no simple and elegant solution to do this completely copy-paste generic.

I am willing, however, to pull your `docker-compose.yaml` in into [examples](https://github.com/bokysan/docker-postfix/tree/master/examples) should you find a configuration that works.
