### ISSUE TITLE
Helm upgrade from 4.1.8 to 4.2.0 failing: mapping key "name" already defined

### ISSUE THREAD

**Issue by m-a-w-i** [bokysan/docker-postfix#196]
When upgrading from helm chart 4.1.8 to 4.2.0 ran into the issue:
```
reconciliation failed: Helm upgrade failed: error while running post render on files: map[string]interface (nil): yaml: unmarshal errors: line 150: mapping key "name" already defined at line 148
```
From what I see this is, because the key `name` is used twice for the new `tmp` volumeMount in the [statefulset template](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/templates/statefulset.yaml#L155)

**Comment by bokysan** [comment]
You are correct. Weird that this was not caught by automated tests.

I'll fix that ASAP.

**Comment by bokysan** [comment]
This commit should have resolved the issue.

Can you please check the `:edge` version (once it compiles) if it's still giving you the problems?

If no, I will publish a fix in the next few hours.

**Comment by m-a-w-i** [comment]
Thanks for the quick fix!
Unfortunately I don't have an environment available, where I can easily run such tests. A released fix I should be able to easily test.

**Comment by m-a-w-i** [comment]
Thanks for the release. I can confirm that it is working.
