### ISSUE TITLE
New Feature: Skip Health Check Logs option, Large Log files

### ISSUE THREAD

**Issue by joel72265** [bokysan/docker-postfix#198]
Thank you for a wonderful application.

**New Feature**: I am using HAproxy (with Health checks enabled) and postfix. This generates logs every second and quickly uses up the free space in postfix. Please have an environment variable to either disable logging Health checks or have some type of logrotate feature.

![Docker-postfix](https://github.com/bokysan/docker-postfix/assets/118885352/225e4868-92fa-44ef-9bc5-bafb544a4072)

I found related posts but the logs are different https://github.com/bokysan/docker-postfix/issues/69

**Comment by bokysan** [comment]
There's no way for me to automagically know how people are going to use this image or where the healthchecks are going to come from, how often and if people will want them logged or not. Hence there is no simple way to "disable logging of health checks".

You, can, however, disable them yourself by simply adding additional rules to `rsyslog` into `/etc/rsyslog.d-before/`.

See example [how this is implemented for local healthchecks](https://github.com/bokysan/docker-postfix/blob/master/configs/rsyslog.conf#L61).

**Comment by joel72265** [comment]
thank you that is help. 

Suggestion: maybe if there is a possibility to have an option like -e IGNORE_HOSTS=192.168.1.X1, 192.168.1.X2 to not store logs from certain hosts that would be great

**Comment by bokysan** [comment]
Sure, that sounds like a good idea. Pull requests are welcome :)
