### ISSUE TITLE
ALLOWED_SENDER_DOMAINS doesn't allow multiple domains

### ISSUE THREAD

**Issue by vladkras** [bokysan/docker-postfix#2]
How's this supposed to work https://github.com/bokysan/docker-postfix/blob/master/postfix.sh#L52

Docker allows env variable to be [KEY=VALUE](https://docs.docker.com/compose/compose-file/#env_file) only and array is not possible, so I can't make what postfix expects - a new line for each domain in **/etc/postfix/allowed_senders**:
```
example.com    OK
example.net    OK
```
I was trying to use space delemiter, comma. etc. in ALLOWED_SENDER_DOMAINS env in docker-compose.yml, this always fails cause
```
example.com example.net    OK
```
is not a vaild config

So how can I pass multiple domains?

**Comment by bokysan** [comment]
There was a bug in the `for` loop -- I've removed the quotes.

To start with multiple sender domains, use the following syntax:
`docker run --rm --name postfix -e "ALLOWED_SENDER_DOMAINS=example.com example.org" -p 587:587 boky/postfix`

This will create the following file:
```
bash-4.3# cd /etc/postfix/
bash-4.3# cat allowed_senders
example.com	OK
example.org	OK
```

Cheers,
B
