### ISSUE TITLE
LDAP lookup map support

### ISSUE THREAD

**Issue by pixil98** [bokysan/docker-postfix#204]
I'm working on deploying this in a kubernetes cluster where I'm using a central idp to manage some user/service accounts. Would it be possible to include the `postfix-ldap` package in this docker image to enable the use of ldap lookup for postfix maps?  It's available for both debian and alpine and is under 500kB (68Kb for alpine) so it shouldn't have a large impact on either image.

If you're open to it, i can submit a PR to add it.

**Comment by bokysan** [comment]
Sure. No objections. PR would be appriciated.
