### ISSUE TITLE
Chart and App version inconsistency when searching the repo

### ISSUE THREAD

**Issue by sivarama-p-raju** [bokysan/docker-postfix#216]
The chart version and app version that is displayed when running ```helm search repo bokysan/mail``` is not consistent.

Sometimes, the chart and app version appear with a "v" and sometimes without.

Here is an example:
```
helm search repo bokysan/mail
NAME        	CHART VERSION	APP VERSION	DESCRIPTION
bokysan/mail	4.3.0        	4.3.0      	An outgoing SMTP mail relay for your applicatio...
```
```
helm search repo bokysan/mail
NAME        	CHART VERSION	APP VERSION	DESCRIPTION
bokysan/mail	v4.3.0       	v4.3.0     	An outgoing SMTP mail relay for your applicatio...
```

Is this expected ?

**Comment by bokysan** [comment]
Yes, unfortunately. See:
- https://github.com/bokysan/docker-postfix/commit/2371eee9434c7d39b23393c449df8ac6b3474e24
- https://github.com/bokysan/docker-postfix/commit/064d31ac1bdba611ca760c8b8fd4b1accfec4f62
- https://github.com/bokysan/docker-postfix/pull/141
