### ISSUE TITLE
Guide for setting this up with Nextcloud

### ISSUE THREAD

**Issue by PopeRigby** [bokysan/docker-postfix#22]
I'm not really sure where to start with setting this up with Nextcloud. Is there a guide I can follow to help me along?

**Comment by bokysan** [comment]
This is really out of scope. Your question is about installation / devops and has nothing to do with any specific features of this project.

I'm closing the issue.


To get you started, however:
- Install [Docker](https://www.docker.com/get-started) or Kubernetes ([k3s](https://k3s.io/) is a good option).
- follow instruction manuals for [nextcloud](https://hub.docker.com/_/nextcloud/)
- follow instructions for installing [docker-postfix](https://github.com/bokysan/docker-postfix#tldr)
- reference the SMTP server from your nextcloud installation (the name will depend on what you've chosen when setting up the Docker / Kubernetes container).

**Comment by PopeRigby** [comment]
Sorry, I just didn't know where else to ask. Thank you.
