### ISSUE TITLE
defined smtpd_restriction_classes not used anywhere; lines can be deleted

### ISSUE THREAD

**Issue by meyca** [bokysan/docker-postfix#24]
The definition in the following lines

https://github.com/bokysan/docker-postfix/blob/ed09d86c8d2970b43224b1ea99e0d2ca9c7e803e/run.sh#L140-L141

is not used at all, so these could be deleted. 

Or am I missing something?

**Comment by bokysan** [comment]
I don't know, I'm going through the Postfix documentation now and trying to understand exactly if it can be really removed or not. If you have any detailed insight, that would be most helpful.

**Comment by bokysan** [comment]
Checked, tested and removed in the latest commit.
