### ISSUE TITLE
Add DKIM selector as custom value from env ?

### ISSUE THREAD

**Issue by shibida** [bokysan/docker-postfix#25]
Hello,

By default, in the opendkim configuration the "mail" value for the selector is hard coded in "run.sh" script.
It could be a good idea to let the user customize this value by configuration.

Regards ,
Yannick P.

**Comment by bokysan** [comment]
Most likely, yes. Are you willing to submit a patch?

**Comment by shibida** [comment]
Ho, no because I don't know how to read env value and put it into the run.sh.
For my needs I have just hard coded the good value, by replacing the "mail" values ...

**Comment by bokysan** [comment]
This is resolved on master.

You can now set `DKIM_SELECTOR` environment variable: https://github.com/bokysan/docker-postfix#dkim

**Comment by shibida** [comment]
I think you forget to change one "mail" hard coded in common-run.sh l239

echo "${domain_dkim_selector}._domainkey.$i $i:**mail**:$private_key" >> /etc/opendkim/KeyTable

**Comment by bokysan** [comment]
Could be -- I'll check.
