### ISSUE TITLE
sleep: invalid number '9999999999999999999'

### ISSUE THREAD

**Issue by krissrex** [bokysan/docker-postfix#30]
I tried to run `docker run --rm --name postfix -e "ALLOWED_SENDER_DOMAINS=example.com" -p 1587:587 boky/postfix` on a Raspberry Pi 2B, which is 32bit armhf/armv7.  

The error message is `sleep: invalid number '9999999999999999999'`.
The issue likely relates to file `scripts/opendkim.sh`.  

The largest possible is "INT_MAX" for uint32: `sleep 4294967295`.
(Likewise, I'd assume the largest for 64bit arch is `9223372036854775807`.

As an alternative, it seems you can do `sleep infinity`.

---
Sleep version: `BusyBox v1.31.1 () multi-call binary.`

**Comment by krissrex** [comment]
A workaround for anyone who encounters this before a fix:

```bash
cat <<'EOT' > opendkim.sh
#!/bin/sh
if [ ! -d /etc/opendkim/keys ]; then
    sleep infinity
elif [ -z "$(find /etc/opendkim/keys -type f ! -name .)" ]; then
    sleep infinity
else
    /usr/sbin/opendkim -D -f -x /etc/opendkim/opendkim.conf
fi
EOT

chmod +x opendkim.sh
```
Then mount the file as a docker volume into the container root folder: `"./opendkim.sh:/opendkim.sh"` .

**Comment by bokysan** [comment]
Thank you for reporting the issue -- I guess I haven't taken into account that 32 bit platforms would treat this differently.

I'll patch it up.
