### ISSUE TITLE
Upgrade issue in k8s

### ISSUE THREAD

**Issue by mcritchlow** [bokysan/docker-postfix#33]
I'm encountering the following when upgrading to the newer `v2.0.1` image:

Note: The initial/first (helm-based) deployment works just fine. However, if I need to do a `helm upgrade` I encounter the issue below. I'm curious if you have any thoughts.

```
★★★★★ POSTFIX STARTING UP ★★★★★

‣ INFO Not setting any timezone for the container

‣ INFO Using json log format for rsyslog.

‣ INFO Using unlimited message size.

‣ INFO Setting smtp_tls_security_level: may

‣ NOTE Will try to deliver emails directly to the final server. Make sure your DNS is setup properly!

‣ INFO Using default private network list for trusted networks.

‣ INFO Debugging is disabled.

‣ INFO Setting up allowed SENDER domains: <snipped>

‣ DEBUG DKIM_AUTOGENERATE not set -- you will need to provide your own keys.

‣ INFO No DKIM keys found, will not use DKIM.

‣ INFO Applying custom postfix setting: hostname=postfix

‣ INFO Applying custom postfix setting: message_size_limit=0

‣ INFO Applying custom postfix setting: myhostname=hifive-68132031-email-7c8ffc9cf8-nrfbd

‣ INFO Applying custom postfix setting: mynetworks=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

‣ NOTE Starting: rsyslog, postfix

2020-08-19 21:23:38,812 INFO Set uid to user 0 succeeded

2020-08-19 21:23:38,814 INFO supervisord started with pid 1

2020-08-19 21:23:39,819 INFO spawned: 'opendkim' with pid 44

2020-08-19 21:23:39,824 INFO spawned: 'postfix' with pid 45

2020-08-19 21:23:39,827 INFO spawned: 'rsyslog' with pid 46

{"@timestamp":"2020-08-19T21:23:39.842521+00:00","type":"syslog_json","tag":":","relayhost":"hifive-68132031-email-7c8ffc9cf8-nrfbd","relayip":"127.0.0.1","logsource":"hifive-68132031-email-7c8ffc9cf8-nrfbd","hostname":"hifive-68132031-email-7c8ffc9cf8-nrfbd","program":"","priority":"46","severity":"6","facility":"5","severity_label":"info","facility_label":"syslog","message":" [origin software=\"rsyslogd\" swVersion=\"8.2004.0\" x-pid=\"46\" x-info=\"https:\/\/www.rsyslog.com\"] start","end_msg":""}

2020-08-19 21:23:39,843 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

{"@timestamp":"2020-08-19T21:23:40.499162+00:00","type":"syslog_json","tag":"postfix\/postfix-script[57]:","relayhost":"hifive-68132031-email-7c8ffc9cf8-nrfbd","relayip":"127.0.0.1","logsource":"hifive-68132031-email-7c8ffc9cf8-nrfbd","hostname":"hifive-68132031-email-7c8ffc9cf8-nrfbd","program":"postfix","priority":"18","severity":"2","facility":"2","severity_label":"crit","facility_label":"mail","message":" fatal: the Postfix mail system is already running","end_msg":""}

2020-08-19 21:23:41,500 INFO exited: postfix (exit status 1; not expected)

2020-08-19 21:23:42,502 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)

2020-08-19 21:23:45,507 INFO success: opendkim entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

2020-08-19 21:24:31,567 WARN received SIGTERM indicating exit request

2020-08-19 21:24:31,568 INFO waiting for opendkim, rsyslog to die

2020-08-19 21:24:31,569 INFO stopped: rsyslog (exit status 0)

2020-08-19 21:24:33,573 INFO stopped: opendkim (terminated by SIGTERM)
```

I get events such as:
```
Normal | Scheduled | Successfully assigned highfive-review/hifive-68132031-email-7c8ffc9cf8-nrfbd to lib-worker2 | 8 minutes ago
-- | -- | -- | --
Normal | Pulling | Pulling image "boky/postfix:v2.0.1" | 8 minutes ago
Normal | Pulled | Successfully pulled image "boky/postfix:v2.0.1" | 8 minutes ago
Normal | Killing | Container hifive-68132031-email failed liveness probe, will be restarted | 7 minutes ago
Normal | Pulled | Container image "boky/postfix:v2.0.1" already present on machine | 7 minutes ago
Normal | Created | Created container hifive-68132031-email | 7 minutes ago
Normal | Started | Started container hifive-68132031-email | 7 minutes ago
Warning | Unhealthy | Readiness probe failed: dial tcp 10.42.8.29:587: connect: connection refused | 6 minutes ago
Warning | Unhealthy | Liveness probe failed: dial tcp 10.42.8.29:587: connect: connection refused | 3 minutes ago
```

And here is the Helm template for the deployment being used: https://gitlab.com/ucsdlibrary/development/email/-/blob/trunk/templates/deployment.yaml

I'm not setting any DKIM environment variables.

Thanks in advance for any thoughts you might have on what changed in this image that might require changes on my end.

**Comment by mcritchlow** [comment]
I should add, the version we were using previously, which hasn't had any issues with helm upgrades is:

```
boky/postfix                           latest                   2d3826433b77    10 months ago    63MB
```

**Comment by bokysan** [comment]
I can't reproduce this issue. I tried installing like this:
```
helm install email-test ucsd-helm/email --set envVars[0].name=ALLOWED_SENDER_DOMAINS --set envVars[0].value=example.org
```

And it seems to work fine. What are the variables you're using to start it?

> And here is the Helm template for the deployment being used: https://gitlab.com/ucsdlibrary/development/email/-/blob/trunk/templates/deployment.yaml

I see you are the author of this chart. I never got around to creating a chart but you have. Would you consider donating it to this project as to include it in the default distribution of `docker-postfix`?

**Comment by mcritchlow** [comment]
> And it seems to work fine. What are the variables you're using to start it?

Sorry, i tried to clarify but didn't use the best language perhaps. The initial `helm install` goes fine. It is when I try and `helm upgrade` that I run into this issue. 

> I see you are the author of this chart. I never got around to creating a chart but you have. Would you consider donating it to this project as to include it in the default distribution of docker-postfix?

In general I'm definitely open to that idea and happy to share it if you like what you see. Until running into this upgrade issue, I've been using the chart happily for a few of our applications. Right now we're distributing the chart using a ChartMuseum instance we're hosting locally. How would you envision hosting it? Should we setup a separate issue for doing this?

**Comment by bokysan** [comment]
I can (kind of) reproduce the said issue.

I used the following code:
```sh
helm install --namespace=email-chart-testing --set image.tag=v2.0.1 --set "envVars[0].name=ALLOWED_SENDER_DOMAINS" --set "envVars[0].value=example.org" --set "persistence.storageClass=microk8s-hostpath" email-test ./

helm upgrade --namespace=email-chart-testing --set image.tag=v2.0.1 --set "envVars[0].name=ALLOWED_SENDER_DOMAINS" --set "envVars[0].value=example.com" --set "persistence.storageClass=microk8s-hostpath" email-test ./

# Notice the change from example.org to example.com to force container recreation
```

I'm left with two containers:
```
kubectl get pods                                                                                             57.6s
NAME                          READY   STATUS    RESTARTS   AGE
email-test-7d76f7ff9b-d5zct   0/1     Running   0          76s
email-test-c4765d485-8q8r2    1/1     Running   0          5m15s
```

The newly created container hangs here:
```
2020-09-04T06:19:13.147857+00:00 CRIT    postfix/postfix-script[54]: fatal: the Postfix mail system is already running
```

I'm guessing the issue is the run file which gets created on the same volume. Investigating.

**Comment by mcritchlow** [comment]
@bokysan - Ah, that makes sense. Thanks, I will test that out and if it works I'll close this out. I should also have some time next week to do a first pass at #34 to get your feedback.

**Comment by mcritchlow** [comment]
Yep, using a StatefulSet fixes the upgrade issue. Will mark this closed, thanks again!

**Comment by juliusrickert** [comment]
Hi @bokysan, I ran into the PID issue today too, as postfix is not stopping gracefully (for me).

Wouldn't it be better to ignore the PID as we're using a StatefulSet anyways?

**Comment by bokysan** [comment]
@juliusrickert I'm not quite sure that postfix not stopping has anything to do with PIDs or the issue mentioned here.

**Comment by juliusrickert** [comment]
@bokysan by the logs, I thought so, but I may be wrong:

> ```
> …
> 2020-08-19 21:23:39,843 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 
> {"@timestamp":"2020-08-19T21:23:40.499162+00:00","type":"syslog_json", …, "message":" fatal: the Postfix mail system is already running","end_msg":""}
> 
> 2020-08-19 21:23:41,500 INFO exited: postfix (exit status 1; not expected)
> …
> ```
