### ISSUE TITLE
Include a Helm chart for docker-postfix

### ISSUE THREAD

**Issue by mcritchlow** [bokysan/docker-postfix#34]
From initial discussion in #33 
> Just include it in the project. Then do a GitHub job to push it to gh-pages and host it directly on GitHub. Like, say Traefik Helm chart

>     Should we setup a separate issue for discussing this?

> Most definitely.

Here's the Helm chart being discussed to potentially port upstream into this repo:

https://gitlab.com/ucsdlibrary/development/email/

Questions:
- What name should the chart be given? I called the chart `email`, which is not very creative, but seemed more direct than `docker-postfix`. Could be `postfix` or?
- Is the chart acceptable 'as-is'? Should we tweak the default `tag` and Chart.yaml version info?
- Other?

I won't be working next week, so I probably wouldn't have time to start on this until early September. But definitely open to putting up a PR for initial discussion.

**Comment by bokysan** [comment]
I suggest you open a PR with the chart and we can then change / update it on the fly before being merged.

**Comment by bokysan** [comment]
This should be resolved in the latest master.
