### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by tacticz** [bokysan/docker-postfix#35]
Hello,

Sorry if this appears as a stupid question, but I couldn't figure out how to log postfix activity to a file [ashamed]

Currently I can successfully run the docker-postfix container, send emails by connecting to it via `telnet` and see the server's activity log in the console window where I issued the `docker run -rm ...` command.

I connected to the running container using the `docker exec -it postfix /bin/bash` command and expected to find the postfix log file inside the `/var/log` directory, unfortunately this directory is empty.

From the research I made, and if I understand correctly, `rsyslog` is used as the login mechanism in the container, and its configuration file is `/etc/rsyslog.conf`, which (mainly) contains 3 templates definitions: devicelog, json and plain. I've tried changing the value of the `-e "LOG_FORMAT="` option (plain or json), which effectively modifies the type of output in the console but still no trace of any file under `/var/log`...

Could someone explain what to do in order to have the postfix logs stored in a log file?

Thank you.

P.S.: the `README.md` indicates that the LOG_FORMAT option can be set to "plain" or "JSON" (uppercase), but when setting the value to "JSON" (uppercase), it generates the following error:
```
2020-09-08 14:46:15,844 INFO spawned: 'rsyslog' with pid 118
rsyslogd:  Could not find template 0 'JSON' - action disabled [v8.2004.0 try https://www.rsyslog.com/e/3003 ]
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 46: errors occured in file '/etc/rsyslog.conf' around line 46 [v8.2004.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.2004.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)
2020-09-08 14:46:15,847 INFO exited: rsyslog (exit status 1; not expected)
2020-09-08 14:46:15,847 INFO gave up: rsyslog entered FATAL state, too many start retries too quickly
```

One needs to use "json" (lowercase) in order to modify the log output format. Maybe should it be modified in the `README.md` file?

**Comment by bokysan** [comment]
Usually, when you run a piece of software in a virutalization environment (be it Docker or Kubernetes), you want all your logs to go to STDOUT and then use the container to manage and sort out the logs.

i.e. with docker you can configure logging drivers [either directly|https://docs.docker.com/config/containers/logging/configure/] or via [docker-compose|https://docs.docker.com/compose/compose-file/#logging].

What's the exact use case you're trying to cover?

**Comment by tacticz** [comment]
Hello @bokysan, and thank you for taking the time to answer my question!

My objective is to have a persistent storage space for the postfix container, like in `docker run ... -v $(pwd)/data/log:/var/log ...`, where I'd store the postfix logs. The objective is double, on one side it would allow to keep track of the general postfix activity and, ultimately, I'd want to integrate the postfix container as a service in a Docker stack and have another container (running my Flask app) access the postfix logs to analyze email delivery bounces.

**Comment by bokysan** [comment]
Makes sense. I'll see what can be done.

In the meantime, you could setup a [syslog docker log](https://docs.docker.com/config/containers/logging/syslog/) and then have syslog output to a plain file, which is then parsed by Flask.

The syslog could run as a docker image ([i'm sure there are several](https://www.google.com/search?client=firefox-b-d&q=syslog+docker+image)) itself and the directory where the log files are stored could be shared with Flask,



/var/lib/docker/containers/<container_id>/<container_id>-json.log

**Comment by tacticz** [comment]
Great!

I'll have a look at the references you gave and try to figure out what can be achieved by routing to a syslog server...
Thanks again!

**Comment by denis-antonik** [comment]
Hello.
Today I faced the same problem, I even started trying other images of postfix, but then I found a solution.
Just add ENV variable in docker-compose
`POSTFIX_maillog_file: "/var/log/mail.log"`
After this logs writed to file, on used volume for /var/log

**Comment by imro2** [comment]
I found that you can also do following:
1. Create rsyslog-additional.conf ("additional" is arbitrary)
2. populate with:
`if $programname == 'postfix' then action(type="omfile" dirCreateMode="0700" FileCreateMode="0644" File="/var/log/postfix/mail.log")`
3. map it via volume to  /etc/rsyslog.d/
```
    volumes:
      - ./rsyslog-additional.conf:/etc/rsyslog.d/rsyslog-additional.conf
```

This will leave the stdout/docker logs intact and will only postfix output to /var/log/postfix/mail.log
