### ISSUE TITLE
DKIM_AUTOGENERATE generates files with mode 600 owned by root:root

### ISSUE THREAD

**Issue by pedroetb** [bokysan/docker-postfix#39]
With autogenerate configuration for DKIM keys, files get created with root owner and group, and then they can't be read by opendkim: `opendkim[84]: can't load key from /etc/opendkim/keys/example.org.private: Permission denied`

**Comment by bokysan** [comment]
Thank you for your report. I will check.

**Comment by bokysan** [comment]
This should be resolved in the latest master.
