### ISSUE TITLE
Using XOAuth2 in postfix

### ISSUE THREAD

**Issue by imartinezortiz** [bokysan/docker-postfix#41]
Hi, I've been playing with this container and https://github.com/tarickb/sasl-xoauth2 to configure XOAuth2 for gmail accounts, so it is not required to enable *less secure applications* that seems to be deprecated and will be disabled in the future (https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html, https://gsuiteupdates.googleblog.com/2020/03/less-secure-app-turn-off-suspended.html).

Are you interested in a PR with this new feature ?.

**Comment by bokysan** [comment]
Sure, would be happy to!

Let's just make it as easy as possible to configure (e.g via setting specific environment variables).
