### ISSUE TITLE
Question: Relayhost and helmchart

### ISSUE THREAD

**Issue by ItsReddi** [bokysan/docker-postfix#45]
Hello,
if this image(helm chart) is used to not sent to a relay server will it spin up his own relayserver if replicas or HPA are set?
or should i setup more than one deployment.

First without Relay - to send to the world
Second with HPA and relaying to first?

Thanks

**Comment by bokysan** [comment]
To the best of my knowledge, Postfix does not offer synchronization of queues between independent postfix installations.

As such, if you use `HorizontalPodAutoscaler` you might run into an issue where the emails would remain in the queue and would only be sent out once the specific instance is spun back up.

At this point I would nod suggest using `HPA` but manual scaling.
