### ISSUE TITLE
DKIM readable check, checks against never existing key

### ISSUE THREAD

**Issue by ItsReddi** [bokysan/docker-postfix#46]
https://github.com/bokysan/docker-postfix/blob/16771d45eba77c3e5b2b71efdff157e01954f712/scripts/common-run.sh#L355

should reflect the configured Variables and not example.com

**Comment by bokysan** [comment]
Thank you for the report.

If you're willing to share a PR, I'd be happy to review it, as I won't be able to fix this straight away.
