### ISSUE TITLE
health check fails because localhost does not resolve

### ISSUE THREAD

**Issue by komasoftware** [bokysan/docker-postfix#48]
health checks are failing because localhost does not resolve (deploying on GCP using ContainerOS)

This health check works for me however (overwriting the base image health check)

```
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 CMD printf "EHLO healthcheck\n" | nc `hostname` 587 | grep -qE "^220.*ESMTP Postfix"

```

or just using 127.0.0.1 instead of the hostname

**Comment by bokysan** [comment]
Interesting. I think it there shouldn't be any issues if we replace `localhost` with `127.0.0.1`.

I'll push it out with the next release.
