### ISSUE TITLE
Latest Dockerhub image not referencing updated Github code changes

### ISSUE THREAD

**Issue by Joel-fogue** [bokysan/docker-postfix#5]
Thanks to @wader(https://github.com/wader) I was able to see this issue when I tried to use this image.
Could you please check that DockerHub is building your latest code changes to github? 
Your Dockerfile on Dockerhub is referencing an older github master head.

The older docker image doesn't SET the `MYNETWORKS` env var while the newer code pushes you did to github `IS SETTING that MYNETWORKS` variable. 
You're copying `postfix.sh` in your older image while your newer changes are` COPYing run.sh`

This is causing people that are pulling your dockerhub image to not have support for `MYNETWORKS` like it was my case and I struggled with this for days until @wader was able to see this discrepancy and point me in the right direction.

**Comment by bokysan** [comment]
Yeah, thanks for the head-up. I'll see what's up with Dockerhub and report back.

**Comment by bokysan** [comment]
Seems that Dockerhub forgot the connection to my GitHub account. After deleting and recreating the image at Dockerhub (...and loosing pull history) and re-initializing the connection to GitHub, the process seems to work now.

Please see if you can pull the latest image properly. I'm closing this issue.
