### ISSUE TITLE
lost connection after EHLO from localhost[127.0.0.1]

### ISSUE THREAD

**Issue by dubachphil** [bokysan/docker-postfix#52]
Hi,

i use your container and i love it, but i've a little problem with 3 log lines each minute.
Sending mails isn't the problem. This works perfectly. The host isn't reachable from the internet.
I just use the container to send mails from a small application.

I've a really short docker-compose file:

```
version: '3'
services:
  mail:
    image: boky/postfix:v2.2.2
    ports:
      - "1587:587"
    environment:
      HOSTNAME: "myhost"
      ALLOWED_SENDER_DOMAINS: "mail.my.domain"
      TZ: "Europe/Zurich"
```

and i get all minute this output in the log:

```
2021-01-26T17:47:29.762763+01:00 INFO    postfix/smtpd[134]: connect from localhost[127.0.0.1]  
2021-01-26T17:47:29.762881+01:00 INFO    postfix/smtpd[134]: lost connection after EHLO from localhost[127.0.0.1]  
2021-01-26T17:47:29.762895+01:00 INFO    postfix/smtpd[134]: disconnect from localhost[127.0.0.1] ehlo=1 commands=1
```
Have you an idea where my problem is?

Thanks for your response

**Comment by bokysan** [comment]
That's expected.

These lines are produced by HEALTCHECK line in Dockerfile.

That's how we ensure that the container is running properly.

If you override the healthcheck `docker-compose.yml` this will dissappear, but there will be no way to detect if the process stops responding.
