### ISSUE TITLE
Allow recepient domains

### ISSUE THREAD

**Issue by demigor** [bokysan/docker-postfix#53]
Hi,

I'm new to postfix so any help would be appreciated.
I need to limit postfix to send mails only to specific domains only. We use it as a development SMTP server and don't want to send mails outside the company.

Is it possible to configure docker container with postfix to somehow limit target domains (white list).

Thank you,
Kind regards

**Comment by bokysan** [comment]
If you're in need of a development SMTP server, may I suggest [Sendria](https://github.com/msztolcman/sendria), [MailHog](https://github.com/mailhog/MailHog) or [MailCatcher](https://mailcatcher.me/)?

**Comment by demigor** [comment]
Thank you for the hint, we may use MailHog for real mail testing functionality.

However what we want is not exactly what development SMTPs (Sendria, MailHog, MailCatcher) currently offer.
We want to white list target domains, so any other mails should not leave the company. 

This is somehow possible with postfix, because there is already ALLOWED_SENDER_DOMAINS parameter.
I just cannot find something like ALLOWED_RECEPIENT_DOMAINS.

Kind regards

**Comment by bokysan** [comment]
Sorry,

this kind of functionality is outside of the scope of this image. This, however, might be supported by Postfix itself and you can influence it either by setting `POSTFIX_<name>` variables and/or putting your init scripts into a `/docker-init.db` directly.

I suggest you look at:
- https://serverfault.com/questions/355972/is-it-possible-to-limit-outgoing-emails-in-postfix-to-one-specific-domain
- http://www.postfix.org/SMTPD_ACCESS_README.html
- http://www.postfix.org/postconf.5.html#smtpd_client_restrictions

and/or ask with your lokal devops group.
