### ISSUE TITLE
Question: use an existing claim

### ISSUE THREAD

**Issue by bcroq** [bokysan/docker-postfix#55]
Actually, when persistence is enabled, this chart creates a Volume and a VolumeClaim.

Could it be possible to configure an existing claim as it is possible in https://github.com/bitnami/charts/tree/master/bitnami/postgresql using `persistence.existingClaim`?

**Comment by bokysan** [comment]
Sure, doable.

If you have a patch ready, merge requests are welcome. If not, I might play around with adding support sometime this month.
