### ISSUE TITLE
Feature: Add RELAY_PASSWORD_FILE using Docker secrets

### ISSUE THREAD

**Issue by waynehaffenden** [bokysan/docker-postfix#56]
It would be great to be able use Docker secrets to store the relay password rather than using plain text using the RELAY_PASSWORD_FILE environment variable.

**Comment by bokysan** [comment]
Good idea.

I'll look into it.

**Comment by bokysan** [comment]
I've checked and it should already be possible to set `RELAYHOST_PASSWORD_FILE`. I'll update the documentation, though.
