### ISSUE TITLE
Reasoning behind smtpd_recipient_restrictions

### ISSUE THREAD

**Issue by tongpu** [bokysan/docker-postfix#62]
I would like to discuss the reasoning behind the configuration for `smtpd_recipient_restrictions` in [`scripts/common-run.sh`](https://github.com/bokysan/docker-postfix/blob/cf2b2be0d3aa6a44542d191edbaa4b504872e52c/scripts/common-run.sh#L227), especially what the recommended way would be for overriding the configuration (e.g. removing `reject_unknown_recipient_domain` to trigger a delivery failure message instead of an error in the SMTP session.

Should I just override it using the environment variable `POSTFIX_smtpd_recipient_restrictions` or is their any other way?

**Comment by bokysan** [comment]
The configuration is there to set sane defaults and least amount of configuration for the majority of use cases.

If you need to override it, either:
- set the environment variable (these get set after everything else is configure) or
- configure your own init scripts and put them in the `/docker-init.db/` directory)

**Comment by tongpu** [comment]
> [...]
> * set the environment variable (these get set after everything else is configure) or

Thanks for the feedback. I saw that the overrides get set after all the other configuration steps, but wanted to make sure that this is also intended in this case.

Thanks a lot for you help.
