### ISSUE TITLE
DKIM not working if ALLOW_EMPTY_SENDER_DOMAINS is set to true ?

### ISSUE THREAD

**Issue by marcwaz** [bokysan/docker-postfix#65]
I have set ALLOW_EMPTY_SENDER_DOMAINS to true while starting my containers. 
With this option, I suppose that it makes no sens to have DKIM_AUTOGENERATE set to true because the container needs to have the list of domain names which need DKIM keys. Is it correct? 
So I have generated the DKIM keys manually through the piece of code provided and set the DNS entries accordingly.
But unfortunately while testing I have discovered that my emails doesn't contain any DKIM signature. The keys are stored in a volume in order to avoid to loose them.
Even if I restart the container, the problem remains. My emails aren't signed (I have checked under Google and used dkimvalidator.com). Does it means that DKIM is not compatible with the option ALLOW_EMPTY_SENDER_DOMAINS ?
I would be great! Because in my case I don't want to provide the list of domain names (which is changing all the time) and don't want to restart the container.
The container logs says:
‣ NOTE  Using custom allowed networks: x.x.x.x/yy
‣ INFO  Debugging is disabled.
‣ INFO  Using default file for SMTP header checks
‣ NOTE  Setting up smtp_header_checks to regexp:/etc/postfix/smtp_header_checks
‣ DEBUG DKIM_AUTOGENERATE not set -- you will need to provide your own keys.
‣ NOTE  Configuring OpenDKIM.
        ...using socket inet:localhost:8891

SPF is working like a charm. Just DKIM which is not working.

**Comment by bokysan** [comment]
This is a really interesting edge case, which is going to be hard to debug.

Would it be possible for you to contribute a test case so I can explore the issue further?

**Comment by bokysan** [comment]
Closing this issue as there was no feedback from @marcwaz.
