### ISSUE TITLE
Can't disable persistant volume

### ISSUE THREAD

**Issue by m4dm4rtig4n** [bokysan/docker-postfix#68]
Hello,

When i disable persistant volume :

```
Error: UPGRADE FAILED: cannot patch "postfix-mail" with kind StatefulSet: StatefulSet.apps "postfix-mail" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Comment by bokysan** [comment]
This is not a chart issue -- Kubernetes does not permit changes to certain fields on the statefulset. If you want to remove the persistent volume, you need to delete and recreate the StatefulSet.
