### ISSUE TITLE
Logs inundated with ehlo healthcheck

### ISSUE THREAD

**Issue by LeorGreenberger** [bokysan/docker-postfix#69]
It is nearly impossible to use the logs to find anything because every 30 seconds the ehlo healthcheck is logged at INFO level:

```
gmail-relay_1  | 2021-05-24T21:02:17.979094-04:00 INFO    postfix/smtpd[27020]: connect from localhost[127.0.0.1]
gmail-relay_1  | 2021-05-24T21:02:17.979120-04:00 INFO    postfix/smtpd[27020]: smtp_stream_setup: maxtime=300 enable_deadline=0
gmail-relay_1  | 2021-05-24T21:02:17.979137-04:00 INFO    postfix/smtpd[27020]: match_hostname: smtpd_client_event_limit_exceptions: localhost ~? 127.0.0.0/8
gmail-relay_1  | 2021-05-24T21:02:17.979144-04:00 INFO    postfix/smtpd[27020]: match_hostaddr: smtpd_client_event_limit_exceptions: 127.0.0.1 ~? 127.0.0.0/8
gmail-relay_1  | 2021-05-24T21:02:17.979155-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 220 6180d6d78afb ESMTP Postfix
gmail-relay_1  | 2021-05-24T21:02:17.979189-04:00 INFO    postfix/smtpd[27020]: watchdog_pat: 0x7f6e69702f20
gmail-relay_1  | 2021-05-24T21:02:17.980647-04:00 INFO    postfix/smtpd[27020]: < localhost[127.0.0.1]: EHLO healthcheck
gmail-relay_1  | 2021-05-24T21:02:17.980678-04:00 INFO    postfix/smtpd[27020]: match_list_match: localhost: no match
gmail-relay_1  | 2021-05-24T21:02:17.980684-04:00 INFO    postfix/smtpd[27020]: match_list_match: 127.0.0.1: no match
gmail-relay_1  | 2021-05-24T21:02:17.980692-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-6180d6d78afb
gmail-relay_1  | 2021-05-24T21:02:17.980700-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-PIPELINING
gmail-relay_1  | 2021-05-24T21:02:17.980706-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-SIZE
gmail-relay_1  | 2021-05-24T21:02:17.980713-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-VRFY
gmail-relay_1  | 2021-05-24T21:02:17.980719-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-ETRN
gmail-relay_1  | 2021-05-24T21:02:17.980731-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-ENHANCEDSTATUSCODES
gmail-relay_1  | 2021-05-24T21:02:17.980738-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-8BITMIME
gmail-relay_1  | 2021-05-24T21:02:17.980746-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250-DSN
gmail-relay_1  | 2021-05-24T21:02:17.981156-04:00 INFO    postfix/smtpd[27020]: > localhost[127.0.0.1]: 250 CHUNKING
gmail-relay_1  | 2021-05-24T21:02:17.981183-04:00 INFO    postfix/smtpd[27020]: watchdog_pat: 0x7f6e69702f20
gmail-relay_1  | 2021-05-24T21:02:17.982017-04:00 INFO    postfix/smtpd[27020]: smtp_get: EOF
gmail-relay_1  | 2021-05-24T21:02:17.982030-04:00 INFO    postfix/smtpd[27020]: match_hostname: smtpd_client_event_limit_exceptions: localhost ~? 127.0.0.0/8
gmail-relay_1  | 2021-05-24T21:02:17.982036-04:00 INFO    postfix/smtpd[27020]: match_hostaddr: smtpd_client_event_limit_exceptions: 127.0.0.1 ~? 127.0.0.0/8
gmail-relay_1  | 2021-05-24T21:02:17.982046-04:00 INFO    postfix/smtpd[27020]: lost connection after EHLO from localhost[127.0.0.1]
gmail-relay_1  | 2021-05-24T21:02:17.982056-04:00 INFO    postfix/smtpd[27020]: disconnect from localhost[127.0.0.1] ehlo=1 commands=1
```

The log also grows at massive rates as a result.

I think a few things can be done to improve this:
1. Don't log healthcheck to stdout 
    * Perhaps change this to log to a file or with a different log level or only log to stderr when healthcheck fails.
2. Add logrotate cron job and optionally allow some settings for this to be set through env variables or a mapped logrotate.d config file.

**Comment by bokysan** [comment]
Dear @LeorGreenberger: 

If there is a way to omit logging of healtchecks, I have not found it yet. If you do know a way, please share your code. Patches are welcome.

If you would like to log to a file, there's already a possibility for that: `POSTFIX_maillog_file: "/var/log/mail.log"`. You can then use another container to do logrotate -- I believe that's outside of the scope of this project.

**Comment by LeorGreenberger** [comment]
Thank you for the quick response! I will investigate if we can omit logging of healthchecks. I saw there is an option to log to a file. If I use this feature and then use another container to do logrotate, will it cause problems with docker-postfix trying to write to a file that has been rotated?

**Comment by malmatheson** [comment]
You can override/disable the image healthchecks when running a container.

The healthcheck arguments to docker run are:

  --health-cmd            Command to run to check health
  --health-interval       Time between running the check
  --health-retries        Consecutive failures needed to report unhealthy
  --health-timeout        Maximum time to allow one check to run
  --health-start-period   Start period for the container to initialize before starting health-retries countdown
  --no-healthcheck        Disable any container-specified HEALTHCHECK

If using docker compose : 

healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 10s

To disable the healthcheck : 

healthcheck:
  disable: true

Reference : https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck
