### ISSUE TITLE
unknown mail transport error

### ISSUE THREAD

**Issue by komasoftware** [bokysan/docker-postfix#75]
Sometimes mails are stuck in the queue with error description "unknown mail transport error". 
When I log into the container and run `postqueue -f`, the mails go through. Not sure if this is an issue with the container image or the receiving end, I have some logging that says : 

 - warning: private/smtp socket: malformed response"
 - Read 141 chars: 250-secure-smtpnodes.otherdomain

Any clues on how to do a root cause analysis ?

![Selection_688](https://user-images.githubusercontent.com/482152/120481678-a122b980-c3b0-11eb-8a7b-748ed61dac75.png)
.nl??250-PIPEL"

**Comment by bokysan** [comment]
I don't know if I can help you much.

However, you do seem to have an error/warning regarding `btree` hash. This was removed in the latest versions of Alpine, so if possible, you should try switching to `lmdb` first and see if that fixes the issue.

**Comment by komasoftware** [comment]
thank you the response. 

I am however still confused on how to try to move to `lmdb` ? Does this require me to install this on the docker container and as such build a custom container based on your Dockerfile ?

Thanks!

**Comment by bokysan** [comment]
Any postfix config that you may have that uses external files (such as aliases) which look like this: `something = btree:/path/to/file` or `something = hash:/path/to/file` need to be replaced with `something = lmdb:/path/to/file`
