### ISSUE TITLE
use different host as relayhost in sasl_passwd

### ISSUE THREAD

**Issue by msvechla** [bokysan/docker-postfix#76]
Hi, 

Thanks for this awesome helm chart!

For some reason our SMTP relay requires a different host in the sasl_passwd file than the actual `RELAYHOST` configured.
Would it be possible to add something like an `SASL_RELAYHOST` variable that will be used instead of the `RELAYHOST` inside the `sasl_passwd` file when specified?

I would be happy to create a PR if you think this makes sense.
Thanks a lot!

**Comment by bokysan** [comment]
Weird flex but OK. Submit a patch and we'll see what can be done.

**Comment by msvechla** [comment]
fyi patch is here, let me know what you think: https://github.com/bokysan/docker-postfix/pull/77
