### ISSUE TITLE
Is it possible to bring your own secret?

### ISSUE THREAD

**Issue by jzandbergen** [bokysan/docker-postfix#92]
Hi Bokysan/All,

I'm checking out this chart which looks really cool. However I don't see an option to define my own secret somewhere in the chart. Am I overlooking something?  Thanks!

**Comment by bokysan** [comment]
Huh, no, not possible at the moment. Pull requests welcome :)

**Comment by jzandbergen** [comment]
Thanks for the fast response! Maybe I will ;)

FYI: I've managed to get a workaround.:
1. Create my own secret in the namespace with the name that corresponds with `<fullname>-mount`.
2. Then set `mountSecret.enabled: true`.
3. Then enter the env vars `RELAYHOST_USERNAME_FILE` and `RELAYHOST_PASSWORD_FILE`.

A bit clunky, so definitely room for improvement there. But hey, it ain't stupid if it works :P
