### ISSUE TITLE
[Bug] RELAYHOST_PASSWORD printed out

### ISSUE THREAD

**Issue by spali** [bokysan/docker-postfix#95]
I assume this is a bug :)
```
‣ NOTE  Forwarding all emails to [mail.example.com]:587 using username relay@example.com and password (redacted).
[mail.example.com]:587 relay@example.com:MYPASSWORD
‣ INFO  Using default private network list for trusted networks.
```
Set via docker compose env variables:
```
      RELAYHOST: ${SMTP_RELAYHOST:?}
      RELAYHOST_USERNAME: ${SMTP_RELAYHOST_USERNAME:?}
      RELAYHOST_PASSWORD: ${SMTP_RELAYHOST_PASSWORD:?}
```

Not sure which line is responsible for the print of the password, but I assume somewhere here: https://github.com/bokysan/docker-postfix/blob/a1a2082ae1652fb5ea90c2ba82020676440b5685/scripts/common-run.sh#L201-L208
Maybe the `grep` should be redirected to /dev/null ?

**Comment by bokysan** [comment]
Thank you for the report.

grep's missing `-q`.
