### ISSUE TITLE
Question: How do I direct emails through this relay when deployed on a kubernetes cluster

### ISSUE THREAD

**Issue by erc7** [bokysan/docker-postfix#96]
I am planning on using this to relay alert emails coming from multiple apps running django on a kubernetes cluster to outlook's smtp server. Is it possible to configure the pod running this service as the django email host?

something like in `django.settings`:
``` 
EMAIL_USE_TLS = True
EMAIL_HOST = 'docker-postfix.svc.cluster.local' <---
EMAIL_PORT = 587
```
not quite sure how to go about directing the emails from the django email backend to docker-postfix, any help would be appreciated.

**Comment by bokysan** [comment]
That's more or less it. You shouldn't use `EMAIL_USE_TLS = True`, unless you have specified a certificate for the Postfix server.

The `EMAIL_HOST` should point to the full name of your service, usually `<service-name>.<namespace>.svc.cluster.local` so you might want to look into that.

That being said, helping people configure Django is kind of outside of the scope of this project. :)
