### ISSUE TITLE
How to connect to a RelayHost via SSL/TLS

### ISSUE THREAD

**Issue by ratzupaltuff** [bokysan/docker-postfix#98]
Hi, 
I want to connect to my relay-host via SSL/TLS on port 465. If I set `RELAYHOST: [example.com]:465` postfix complains in the logs: `postfix/smtp[202]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)` when I try to send an email.
I tried setting `RELAYHOST_TLS_LEVEL=encrypt` and `RELAYHOST_TLS_LEVEL=dane` but the error persisted. Can someone help me how to configure a relayhost connection via SSL/TLS on port 465?
Note: With STARTTLS on port 587 I can send emails.

**Comment by bokysan** [comment]
You will most likely need to configure [smtp_tls_policy_map](http://www.postfix.org/postconf.5.html#smtp_tls_policy_maps).

See also [this example](https://github.com/bokysan/docker-postfix/blob/master/examples/docker/mail-station/docker-compose.yml#L88).

That being said, configuring SMTP is outside of the scope of this image. If you still can't make heads and tails of it, I suggest looking up postfix-specific help groups and mailing lists.

**Comment by maxid** [comment]
why not support "smtp_tls_wrappermode" param setting?
